version: "3.8"
services:
  api:
    container_name: semaphore-api
    env_file: .env
    build: 
      context: .
      dockerfile: ./Dockerfile
    image: moisestabar013/semaphore-api
    ports: 
      - "5000:5000"
